_wandb:
    value:
        cli_version: 0.27.0
        e:
            72l7rfgpmakszwvpoqbbai3mxb7x8wq3:
                codePath: phase4_pipeline.py
                codePathLocal: phase4_pipeline.py
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "13.2"
                disk:
                    /:
                        total: "1020900929536"
                        used: "314427666432"
                email: rdineshmc14@gmail.com
                executable: C:\Dinesh\AutoML\ML-Builder\.venv\Scripts\python.exe
                git:
                    commit: c0f811540d88002bb1696a85d9565a294154a8ab
                    remote: https://github.com/dineshmc1/ML-Builder.git
                gpu: NVIDIA RTX A4000
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6144
                      memoryTotal: "17171480576"
                      name: NVIDIA RTX A4000
                      uuid: GPU-c501c92d-91d9-7c13-a0f0-2f5fec2decbf
                host: mtds_8
                memory:
                    total: "136633843712"
                os: Windows-11-10.0.26200-SP0
                program: C:\Dinesh\AutoML\ML-Builder\phase4_pipeline.py
                python: CPython 3.12.13
                root: C:\Dinesh\AutoML\ML-Builder
                startedAt: "2026-05-20T07:08:17.898794Z"
                writerId: 72l7rfgpmakszwvpoqbbai3mxb7x8wq3
        m: []
        python_version: 3.12.13
        t:
            "1":
                - 5
                - 6
                - 8
                - 53
                - 95
            "2":
                - 1
                - 5
                - 6
                - 8
                - 53
                - 95
            "3":
                - 2
                - 13
                - 16
            "4": 3.12.13
            "5": 0.27.0
            "8":
                - 3
            "10":
                - 20
            "12": 0.27.0
            "13": windows-amd64
alpha:
    value: 0.6
beta:
    value: 0.3
encoder_epochs:
    value: 100
encoder_input_dim:
    value: 17
encoder_output_dim:
    value: 32
gamma:
    value: 0.1
k_neighbors:
    value: 5
lambda_sensitivity:
    value: 0.5
memory_index_path:
    value: memory_store.faiss
n_models_clf:
    value: 14
n_models_reg:
    value: 15
n_test_datasets:
    value: 33
n_train_datasets:
    value: 130
similarity_floor:
    value: 0.75
