import nbformat as nbf
import os

def create_eda_notebook(csv_path: str, profile: dict, output_path: str = 'dataset_exploration.ipynb'):
    """Generates an Exploratory Data Analysis Jupyter Notebook using nbformat."""
    
    nb = nbf.v4.new_notebook()
    
    # 1. Title and Overview
    title_cell = nbf.v4.new_markdown_cell(f"# Exploratory Data Analysis\\n**Dataset**: `{csv_path}`\\n\\nThis notebook was auto-generated by the MetaAutoML Data Understanding Agent.")
    
    # 2. Imports
    imports_cell = nbf.v4.new_code_cell("""import pandas as pd\\nimport numpy as np\\nimport matplotlib.pyplot as plt\\nimport seaborn as sns\\nimport warnings\\nwarnings.filterwarnings('ignore')\\n\\nsns.set_theme(style='whitegrid')""")
    
    # 3. Data Loading
    # Use raw string formatting to avoid escape character issues in paths
    safe_path = csv_path.replace("\\\\", "/")
    loading_cell = nbf.v4.new_code_cell(f"df = pd.read_csv('{safe_path}')\\ndf.head()")
    
    # 4. Info & Missing Values
    info_cell = nbf.v4.new_code_cell("""print(f"Dataset Shape: {df.shape}")\\nprint("\\\\nMissing Values:")\\nprint(df.isnull().sum()[df.isnull().sum() > 0])""")
    
    missing_plot_cell = nbf.v4.new_code_cell("""plt.figure(figsize=(10, 6))\\nsns.heatmap(df.isnull(), yticklabels=False, cbar=False, cmap='viridis')\\nplt.title('Missing Values Heatmap')\\nplt.show()""")

    # 5. Target Analysis
    target_col = profile.get("target_column", "")
    target_cell = []
    if target_col:
        target_md = nbf.v4.new_markdown_cell(f"## Target Analysis: `{target_col}`")
        if profile.get("problem_type") == "classification":
            target_code = nbf.v4.new_code_cell(f"""plt.figure(figsize=(8, 5))\\nsns.countplot(data=df, x='{target_col}', palette='Set2')\\nplt.title('Target Class Distribution')\\nplt.show()""")
        else:
            target_code = nbf.v4.new_code_cell(f"""plt.figure(figsize=(8, 5))\\nsns.histplot(data=df, x='{target_col}', kde=True, color='blue')\\nplt.title('Target Distribution')\\nplt.show()""")
        target_cell = [target_md, target_code]

    # 6. Correlation Heatmap
    corr_md = nbf.v4.new_markdown_cell("## Correlation Analysis (Numeric Features)")
    corr_cell = nbf.v4.new_code_cell("""numeric_df = df.select_dtypes(include=[np.number])\\nif not numeric_df.empty and numeric_df.shape[1] > 1:\\n    plt.figure(figsize=(12, 8))\\n    corr = numeric_df.corr()\\n    sns.heatmap(corr, annot=False, cmap='coolwarm', center=0)\\n    plt.title('Numeric Correlation Matrix')\\n    plt.show()\\nelse:\\n    print("Not enough numeric columns for correlation matrix.")""")

    # 7. Auto-Insights
    insights_text = "## AI Insights\\n"
    notes = profile.get("notes", "No specific insights provided.")
    insights_text += f"- {notes}\\n"
    
    insights_cell = nbf.v4.new_markdown_cell(insights_text)

    # Compile Notebook
    cells = [title_cell, imports_cell, loading_cell, info_cell, missing_plot_cell]
    if target_cell:
        cells.extend(target_cell)
    cells.extend([corr_md, corr_cell, insights_cell])
    
    nb['cells'] = cells
    
    with open(output_path, 'w', encoding='utf-8') as f:
        nbf.write(nb, f)
        
    return output_path
